import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {FLOWS,Index,route,rewrite,chunksFromPages,answerQuestion,propose,replayCandidate,metrics,bucket} from '../web/core.mjs';
import {execute,num,DEFAULTS} from '../web/tools.mjs';import {parseCSV,csvText} from '../web/parsers.mjs';
const rows=JSON.parse(readFileSync(new URL('../web/knowledge.json',import.meta.url))),fixtures=JSON.parse(readFileSync(new URL('../web/fixtures.json',import.meta.url))),ix=new Index(rows);
test('all eleven workflows registered',()=>assert.equal(Object.keys(FLOWS).length,11));
for(const [q,f]of [['商业银行的四个职能','finance_learning'],['支付中介和信用中介','finance_learning'],['发行排期遇非工作日','issuance'],['生成Word发行材料','material_fill'],['净值产品对标','wealth_benchmark'],['周报缺数','weekly_report'],['KYC开户字段时点','onboarding'],['案件邮件KEP核查','kep'],['特征计数策略','strategy'],['三表勾稽','statements'],['客服工单转人工','service'],['FOF基金研究','fund_research']])test('route '+q,()=>assert.equal(route(q,ix).flow,f));
test('complete bank functions including fourth point',()=>{const a=answerQuestion('商业银行的四个职能是什么',ix);assert.equal(a.sources[0].id,'learn-014');for(const x of ['信用中介','支付中介','信用创造','金融服务'])assert.ok(a.answer.includes(x));assert.equal(a.mode,'lexical_extractive')});
test('no evidence does not invent answer',()=>assert.equal(answerQuestion('银河系外星飞船维修许可证',ix,{flow:'finance_learning'}).mode,'no_evidence'));
test('unknown task can request clarification',()=>assert.equal(route('zxqv9988',ix).flow,null));
test('non-active facts not retrieved',()=>{const i=new Index([{id:'x',title:'秘密政策',content:'秘密政策',status:'pending_review',flow:'service'}]);assert.equal(i.search('秘密').length,0)});
test('multi-round query retained separately',()=>{const r=rewrite('那它有什么功能','商业银行');assert.equal(r.original,'那它有什么功能');assert.ok(r.expanded.includes('商业银行'));assert.ok(r.followup)});
test('chunk content covers complete source without losing tail',()=>{const text='甲乙丙丁'.repeat(500)+'末尾最后内容',cs=chunksFromPages([{page:7,text}],{id:'x',title:'test'});assert.ok(cs.at(-1).content.endsWith('末尾最后内容'));assert.ok(cs.every(c=>c.page===7&&c.content.length<=650))});
test('metrics recall differs from hit',()=>assert.deepEqual(metrics(['a','x'],['a','b']),{hit:1,recall:.5,mrr:1}));
test('stable bucket',()=>assert.equal(bucket('abc'),bucket('abc')));
test('loop alters retrieval and keeps bounded top k',()=>{const p=propose([{id:'f',flow:'issuance',terms:'顺延',trace_id:'t',category:'retrieval'}]);assert.equal(p.topK,8);const r=replayCandidate(p,[{id:'t',query:'发行排期',flow:'issuance'}],rows);assert.equal(r.pairs.length,1);assert.equal(r.passed,true)});
for(const [name,p]of Object.entries(DEFAULTS))test('actual tool executes '+name,()=>{const r=execute(name,p,fixtures);assert.ok(r.rows.length);assert.equal(r.synthetic,true)});
test('calendar agrees with synthetic python baseline',()=>assert.equal(execute('issuance',{},fixtures).rows[0]['成立日'],'2026-09-28'));
test('leading zeros and missing values',()=>{const r=execute('weekly_report',{},fixtures);assert.ok(r.rows[0]['登记编码'].startsWith('00'));assert.ok(r.rows.some(x=>x['区间收益率']===null))});
test('future unavailable features',()=>assert.equal(execute('onboarding',{},fixtures).rows.find(r=>r.field==='bank_link').available_now,false));
test('email ambiguity distinct from absence',()=>{const r=execute('kep',{},fixtures);assert.ok(r.rows.some(x=>x.status==='ambiguous'));assert.ok(r.rows.some(x=>x.status==='not_found_needs_review'))});
test('strategy cannot go live',()=>assert.equal(execute('strategy',{},fixtures).candidate.status,'disabled'));
test('bad date and bad numbers rejected',()=>{assert.throws(()=>execute('issuance',{start:'2026-02-31'},fixtures));assert.throws(()=>num('NaN'));assert.throws(()=>num('3%'));assert.equal(num('(3.5)'),-3.5)});
test('CSV parser handles quotes, unicode and zeros',()=>{const r=parseCSV('\uFEFFid,name\n001,"hello,世界"\n');assert.equal(r[0].id,'001');assert.equal(r[0].name,'hello,世界')});
test('CSV escaped spreadsheet formulas',()=>assert.ok(csvText([{x:'=HYPERLINK("x")'}]).includes("'=HYPERLINK")));
