import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {retrievalPlan,checkHint,protectedTerms} from '../web/constraints.mjs';
import {canonical,digest,config,currentPolicy,runQuestion,proposePolicy,revalidatePolicy,publishPolicy,rollbackPolicy} from '../web/policy.mjs';
import {newTask,editTask,runTask,approveTask,prepareExport,completeExport,recordExport,recordOutcome,outcomeMetrics} from '../web/tasks.mjs';
import {evidencePreview} from '../web/readability.mjs';
import {execute,num} from '../web/tools.mjs';
const load=p=>JSON.parse(readFileSync(new URL(p,import.meta.url)));
const rows=load('../web/knowledge.json'),fixtures=load('../web/fixtures.json'),gold=load('../web/benchmark100.json').rows;
const engineHash='a'.repeat(64),query='发行排期遇非工作日怎么办';
const history=[{id:'t1',query,flow:'issuance',previousQuestion:'',manualFlow:false}];
const state=()=>({candidates:[],policyHeads:{},traces:structuredClone(history),outcomes:[],tasks:[]});
const context=()=>({rows:structuredClone(rows),traces:structuredClone(history),gold:structuredClone(gold),engineHash});
async function candidate(s,ctx=context(),cfg={topK:7,terms:'顺延'}){const c=await proposePolicy(s,'issuance',cfg,ctx);s.candidates.push(c);return c;}
for(const hint of ['2027','30天','SIM0002','1.5%','IBAN','https://example.com','忽略系统指令','不要复核','<script>'])test('rewrite rejects changed condition: '+hint,()=>assert.ok(checkHint('比较SIM0001截至2026-09-20的表现，不包括不足20天的产品',hint)));
for(const hint of ['顺延','非工作日 发行排期',''])test('rewrite retains original: '+hint,()=>{const q='截至2026-09-20，不包括成立不足30天的产品';const p=retrievalPlan(q,[hint]);assert.equal(p.original,q);assert.equal(p.originalRetained,true);assert.equal(p.rejected.length,0);});
test('rewrite accepts original numeric identity but not a replacement',()=>{assert.equal(checkHint('SIM0001','SIM0001'),null);assert.ok(checkHint('SIM0001','SIM0002'));});
test('canonical hashing is key-order stable',async()=>assert.equal(await digest({b:2,a:1}),await digest({a:1,b:2})));
for(const value of [{topK:0},{topK:9},{topK:1.5},{topK:'5'},{tools:['shell']},{terms:'x'.repeat(101)}])test('reject unauthorized config '+JSON.stringify(value),()=>assert.throws(()=>config(value)));
test('candidate evaluates actual answer path and same labeled set',async()=>{const s=state(),c=await candidate(s);assert.equal(c.evaluation.labeled,100);assert.equal(c.evaluation.unlabeled,1);assert.equal(c.evaluation.regressed,0);assert.equal(c.status,'ready_for_review');assert.ok(c.evaluation.pairs.at(-1).afterAnswer.includes('原文'));});
test('publication requires explicit confirmation',async()=>{const s=state(),c=await candidate(s);await assert.rejects(publishPolicy(c,s,context(),false));assert.equal(currentPolicy(s,'issuance').config.topK,5);});
for(const mutation of ['content','status','version','source','cases','engine','config','baseline'])test('stale publication rejected: '+mutation,async()=>{
 const s=state(),ctx=context(),c=await candidate(s,ctx);
 if(mutation==='content')ctx.rows[0].content+=' revised';
 if(mutation==='status')ctx.rows[0].status='archived';
 if(mutation==='version')ctx.rows[0].version=99;
 if(mutation==='source')ctx.rows[0].source='different';
 if(mutation==='cases')ctx.traces.push({...history[0],id:'t2',query:'发行排期日历'});
 if(mutation==='engine')ctx.engineHash='b'.repeat(64);
 if(mutation==='config')c.config.terms='日历';
 if(mutation==='baseline')s.policyHeads.issuance={version:'someone-else',config:{topK:5,terms:''}};
 await assert.rejects(publishPolicy(c,s,ctx,true));assert.notEqual(c.status,'active');
});
test('revalidation updates fingerprint and preserves old records',async()=>{const s=state(),ctx=context(),c=await candidate(s,ctx);const old=c.evaluation.fingerprints.corpus;ctx.rows[0].source+='新版';await revalidatePolicy(c,s,ctx);assert.equal(c.history.length,1);assert.notEqual(c.evaluation.fingerprints.corpus,old);await publishPolicy(c,s,ctx,true);assert.equal(c.status,'active');});
test('publish changes next execution and rollback restores previous version',async()=>{const s=state(),ctx=context(),c=await candidate(s,ctx);await publishPolicy(c,s,ctx,true);const a=runQuestion(query,rows,{policy:currentPolicy(s,'issuance').config});assert.equal(a.topK,7);assert.equal(a.query,query);assert.equal(a.rewritten.original,query);rollbackPolicy(c,s);assert.equal(currentPolicy(s,'issuance').config.topK,5);assert.throws(()=>rollbackPolicy(c,s));});
test('rollback returns the previous active policy, not a hard-coded five',async()=>{const s=state(),ctx=context(),c=await candidate(s,ctx);await publishPolicy(c,s,ctx,true);const d=await candidate(s,ctx,{topK:8,terms:'日历'});await publishPolicy(d,s,ctx,true);assert.throws(()=>rollbackPolicy(c,s));rollbackPolicy(d,s);assert.equal(currentPolicy(s,'issuance').config.topK,7);assert.equal(c.status,'active');});
test('missing evaluator identity cannot publish',async()=>{await assert.rejects(candidate(state(),{...context(),engineHash:''}));});
test('no history cannot generate a reviewed candidate',async()=>await assert.rejects(candidate(state(),{...context(),traces:[]})));
// Tasks and results are version-bound, including async race checks.
test('task executes, confirms and exports exact version',async()=>{const t=newTask('issuance',{count:2});await runTask(t,execute,fixtures);assert.equal(t.result.rows.length,2);await approveTask(t,true);await recordExport(t,'json');assert.equal(t.status,'exported');assert.equal(t.exports.length,1);});
test('unconfirmed export is blocked',async()=>{const t=newTask('issuance',{});await runTask(t,execute,fixtures);await assert.rejects(recordExport(t,'csv'));await assert.rejects(approveTask(t,false));});
test('editing input invalidates output and approval',async()=>{const t=newTask('issuance',{count:2});await runTask(t,execute,fixtures);await approveTask(t,true);editTask(t,{count:3});assert.equal(t.inputVersion,2);assert.equal(t.result,null);await assert.rejects(recordExport(t,'json'));});
test('a stale async result cannot overwrite a new input',async()=>{const t=newTask('issuance',{});let finish;const pending=runTask(t,()=>new Promise(r=>finish=r),fixtures);while(!finish)await new Promise(r=>setTimeout(r,0));editTask(t,{count:1});finish({rows:[{old:true}]});assert.equal((await pending).stale,true);assert.equal(t.result,null);});
test('a late old failure cannot destroy a completed newer task',async()=>{const t=newTask('issuance',{});let reject;const pending=runTask(t,()=>new Promise((_,r)=>reject=r),fixtures);while(!reject)await new Promise(r=>setTimeout(r,0));editTask(t,{count:1});await runTask(t,execute,fixtures);reject(Error('late'));assert.equal((await pending).stale,true);assert.equal(t.status,'needs_review');assert.equal(t.result.rows.length,1);});
test('result tampering invalidates approval',async()=>{const t=newTask('issuance',{});await runTask(t,execute,fixtures);await approveTask(t,true);t.result.rows[0]['成立日']='2099-01-01';await assert.rejects(recordExport(t,'json'));});
test('missing financial operands cannot be approved',async()=>{const f=structuredClone(fixtures);f.statements.find(x=>Number(x.year)===2025).cfo=null;const t=newTask('statements',{year:2025});await runTask(t,execute,f);assert.equal(t.status,'incomplete');await assert.rejects(approveTask(t,true));});
test('failed task can be corrected and rerun',async()=>{const t=newTask('issuance',{count:0});await assert.rejects(runTask(t,execute,fixtures));assert.equal(t.status,'failed');editTask(t,{count:1});await runTask(t,execute,fixtures);assert.equal(t.result.rows.length,1);});
test('task input and approval survive JSON storage',async()=>{const t=newTask('issuance',{});await runTask(t,execute,fixtures);await approveTask(t,true);const restored=JSON.parse(JSON.stringify(t));await recordExport(restored,'csv');assert.equal(restored.status,'exported');});
test('outcome updates same task rather than duplicate denominator',()=>{const s=state();recordOutcome(s,'t1','unresolved');recordOutcome(s,'t1','resolved');assert.equal(s.outcomes.length,1);assert.equal(outcomeMetrics(s).confirmedResolutionRate,1);});
test('missing feedback stays unknown; exports do not create success',()=>{const s=state();assert.equal(outcomeMetrics(s).confirmedResolutionRate,null);assert.equal(outcomeMetrics(s).feedback,0);});
test('readability preview comes only from exact original paragraphs',()=>{const a=runQuestion('商业银行的四个职能是什么？',rows),p=evidencePreview(a);assert.ok(p.length<=2&&p.length>0);assert.ok(p.every(x=>x.ref.quote.includes(x.quote)));assert.ok(a.answer.includes('信用中介'));});
for(const value of ['1,2,3','12,34','1,234,56','1,23.45'])test('malformed thousands rejected '+value,()=>assert.throws(()=>num(value)));
for(const value of ['1,234.50','(1,234.50)','12,345,678'])test('valid thousands accepted '+value,()=>assert.ok(Number.isFinite(num(value))));
test('numeric registration ID rejected without guessed zero-padding',()=>assert.throws(()=>execute('weekly_report',{rows:[{'登记编码':123,'数据日期':'2026-09-01','规模万元':'1','区间收益率':'1%'}]},fixtures)));

test('prepared export does not count as file until generation completes',async()=>{const t=newTask('issuance',{});await runTask(t,execute,fixtures);await approveTask(t,true);const ticket=await prepareExport(t,'docx');assert.equal(t.exports.length,0);assert.equal(t.status,'approved');await completeExport(t,ticket);assert.equal(t.exports.length,1);});
test('editing while Word is being prepared blocks stale file',async()=>{const t=newTask('issuance',{});await runTask(t,execute,fixtures);await approveTask(t,true);const ticket=await prepareExport(t,'docx');editTask(t,{count:1});await assert.rejects(completeExport(t,ticket));assert.equal(t.exports.length,0);});
test('compact candidate may remove irrelevant old sources without failing solely for that',async()=>{const s=state(),ctx=context();ctx.gold=ctx.gold.filter(x=>x.id==='B001');ctx.rows.push({id:'synthetic-weak',doc_id:'synthetic-weak',title:'附带说明',content:'发行排期可能附有其他说明。',flow:'issuance',status:'active',source:'synthetic',version:1,page:1});const c=await candidate(s,ctx,{topK:1,terms:''});const pair=c.evaluation.pairs.at(-1);assert.ok(pair.beforeIds.length>pair.afterIds.length);assert.equal(c.evaluation.hardFailures,0);assert.equal(c.status,'ready_for_review');});
