import {route,answerQuestion} from './assurance.mjs';
import {FLOWS,Index,propose,replayCandidate,metrics} from './core.mjs';
import {openStore,downloadBlob} from './storage.mjs';
import {parseFile,parseCSV,csvText,wordBlob} from './parsers.mjs';
import {execute,DEFAULTS} from './tools.mjs';
const $=id=>document.getElementById(id), E=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e},now=()=>new Date().toISOString();
const jpre=x=>E('pre',JSON.stringify(x,null,2)), button=(text,fn,cls='')=>{const b=E('button',text,cls);b.onclick=()=>guard(()=>fn(b));return b}, panel=title=>{const p=E('div',undefined,'panel');if(title)p.append(E('h2',title));return p},row=()=>E('div',undefined,'row');
const wrap=$('content');let seed=[],fixtures={},index,db,state,last=null,memoryOnly=false,selectedFlow='auto';
const fresh=()=>({schema:5,docs:[],traces:[],feedback:[],candidates:[],preferences:{},pilot:[],consent:false,session:'s-'+crypto.randomUUID(),lastFlow:null,lastQuestion:'',events:[],tickets:[]});
async function guard(fn){try{await fn()}catch(e){notice(e.message||String(e),'error');console.error(e)}}
function notice(text,cls='success'){$('notice').className=cls;$('notice').textContent=text;}
function activeRows(){return [...seed,...state.docs.flatMap(d=>d.chunks.map(c=>({...c,status:d.status,flow:d.flow,version:d.version})))];}
function refreshIndex(){index=new Index(activeRows());$('runtime').textContent=`${activeRows().filter(c=>c.status==='active').length.toLocaleString()} 个可检索片段 · 浏览器模式`;}
async function save(){if(db)try{await db.save('workspace',state)}catch{memoryOnly=true;notice('存储额度不足：当前内存仍可使用，刷新可能丢失。请导出工作区。','warning')}else memoryOnly=true;}
function log(type,detail){state.events.push({at:now(),type,detail});state.events=state.events.slice(-150);}
const TABS=[['ask','学习与问答'],['library','资料与上传'],['tools','业务工具'],['traces','执行记录'],['loop','反馈与策略'],['memory','记忆工作台'],['eval','回放与评测'],['pilot','体验记录'],['guide','原理与部署']];
function mount(name){wrap.replaceChildren();$('notice').textContent='';document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$('heading').textContent=TABS.find(t=>t[0]===name)?.[1]||name;({ask:showAsk,library:showLibrary,tools:showTools,traces:showTraces,loop:showLoop,memory:showMemory,eval:showEval,pilot:showPilot,guide:showGuide})[name]();}
function flowSelect(id,all=false){const s=E('select');s.id=id;if(all)s.append(new Option('自动识别工作流','auto'));for(const[k,v]of Object.entries(FLOWS))s.append(new Option(v[0],k));return s;}
function field(type,value,id){const i=E('input');i.type=type;i.id=id;i.value=value??'';return i}
function label(text,input){const l=E('label',text);l.append(input);return l}
function details(title,body){const d=E('details');d.append(E('summary',title),body);return d}
function table(rows,limit=120){const div=E('div',undefined,'tablewrap');if(!rows?.length){div.append(E('p','没有行数据','muted'));return div}const t=E('table'),head=E('thead'),hr=E('tr'),cols=[...new Set(rows.flatMap(r=>Object.keys(r)))];cols.forEach(c=>hr.append(E('th',c)));head.append(hr);t.append(head);const body=E('tbody');for(const r of rows.slice(0,limit)){const tr=E('tr');cols.forEach(c=>tr.append(E('td',typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'—'))));body.append(tr)}t.append(body);div.append(t);if(rows.length>limit)div.append(E('p',`预览前${limit}行，导出保留全部${rows.length}行。`,'muted'));return div;}
function modal(title,body){$('viewer-title').textContent=title;$('viewer-body').replaceChildren(body);if(!$('viewer').open)$('viewer').showModal();}
$('close-viewer').onclick=()=>$('viewer').close();$('viewer').onclick=e=>{if(e.target===$('viewer'))$('viewer').close()};
function showDocument(id,focusPage=null){
 const doc=state.docs.find(x=>x.id===id),rs=activeRows().filter(x=>x.doc_id===id),title=doc?.title||rs[0]?.title||id,body=E('div');
 body.append(E('p',doc?`${doc.parser} · ${doc.status} · ${doc.chunks.length}片 · 仅当前浏览器`:'内置的是重新整理的学习提要/模拟文档，不是上传笔记全文。','muted'));
 const pages=doc?.pages?.length?doc.pages:rs.map((r,i)=>({page:r.page??i+1,text:r.content}));let at=Math.max(0,pages.findIndex(p=>p.page===focusPage));const controls=row(),select=E('select'),area=E('div');
 pages.forEach((p,i)=>select.append(new Option('第'+p.page+'页 / 片段 '+(i+1),String(i))));
 function draw(){select.value=String(at);area.replaceChildren(E('div',pages[at]?.text||'没有可显示的正文','page-text'));}
 select.onchange=()=>{at=Number(select.value);draw()};controls.append(button('上一页',()=>{at=Math.max(0,at-1);draw()}),select,button('下一页',()=>{at=Math.min(pages.length-1,at+1);draw()}));controls.classList.add('modal-nav');
 body.append(controls,area,E('p',`完整保留 ${pages.length} 个页面/片段，可逐页查看。回答预览的长度限制不截断这里的资料。`,'muted'),button('导出全部提取文字',()=>downloadBlob(new Blob([pages.map(p=>'\n【第'+p.page+'页】\n'+p.text).join('\n')],{type:'text/plain;charset=utf-8'}),title+'.txt')));draw();modal(title,body);
}
const EXAMPLES=['商业银行的四个职能是什么？','支付中介和信用中介有什么区别？','解释直接融资和间接融资','货币乘数和存款扩张倍数一样吗？','发行排期遇到非工作日怎么办？','周报登记编码的前导零如何保留？'];
function showAsk(){const intro=panel();intro.classList.add('intro');intro.append(E('h2','先找依据，再给出可核对的结果。'),E('p','内置56个金融基础主题及模拟业务资料。自动选择11类工作流，也可上传自己的资料并查看完整来源。','muted'));wrap.append(intro);
 const p=panel('提出问题'),r=row(),select=flowSelect('ask-flow',true);select.value=selectedFlow;select.onchange=()=>selectedFlow=select.value;const q=E('textarea');q.id='ask-question';q.placeholder='例如：商业银行有哪些职能？支付中介与信用中介有什么区别？';
 const go=button('检索并作答',async b=>{b.disabled=true;try{await ask(q.value,select.value)}finally{b.disabled=false}},'primary');go.id='ask-submit';
 r.append(select,go,button('新会话',async()=>{state.lastQuestion='';state.lastFlow=null;state.session='s-'+crypto.randomUUID();await save();notice('已开启新会话，过去的Trace仍保留。')}));p.append(q,r);const examples=row();EXAMPLES.forEach(x=>examples.append(button(x,()=>{q.value=x},'subtle')));p.append(details('试试这些问题',examples));const result=E('div');result.id='ask-result';wrap.append(p,result);if(last)renderAnswer(last,result);q.onkeydown=e=>{if(e.ctrlKey&&e.key==='Enter')go.click()};}
async function ask(q,chosen='auto'){
 q=q.trim();if(!q||q.length>2000)throw Error('请输入1—2000字的问题');const routing=chosen==='auto'?route(q,index,state.lastFlow):{flow:chosen,mode:'manual',reason:'用户手选工作流'};
 const policy=[...state.candidates].reverse().find(c=>c.status==='active'&&c.flow===routing.flow);const effective=q+(policy?.terms?' '+policy.terms:'');
 const a=answerQuestion(effective,index,{flow:routing.flow,last:state.lastQuestion,topK:policy?.topK||5});a.query=q;if(a.rewritten)a.rewritten.original=q;a.route=routing;a.id='trace-'+crypto.randomUUID();a.session=state.session;a.at=now();a.strategy=policy?{id:policy.id,scope:'仅当前浏览器',topK:policy.topK}:null;
 if(routing.flow&&DEFAULTS[routing.flow])try{a.tool=execute(routing.flow,DEFAULTS[routing.flow],fixtures);a.tool.scope='模拟默认参数，改参数请到业务工具';}catch(e){a.tool_error=e.message}
 last=a;state.traces.push(a);state.traces=state.traces.slice(-80);state.lastQuestion=q;state.lastFlow=a.flow||null;log('Execute',{trace_id:a.id,flow:a.flow,mode:a.mode});await save();if($('ask-result')){renderAnswer(a,$('ask-result'));$('ask-result').scrollIntoView({behavior:'smooth',block:'start'})}
}
function renderAnswer(a,target){target.replaceChildren();const p=panel('回答与依据');p.append(E('span',`${FLOWS[a.flow]?.[0]||'待澄清'} · 分词检索整理`,'badge'),E('p',a.route?.reason||'','muted'));
 if(a.sources?.length){const first=a.sources[0];p.append(E('div',first.content,'answer answer-summary'),E('small',`来源1 · ${first.title} · ${first.source}${first.page?' · 第'+first.page+'页':''}`));if(a.sources.length>1){const extra=details('其他相关依据（'+(a.sources.length-1)+'条）',E('div',a.sources.slice(1).map((s,i)=>`【来源${i+2}】${s.title}\n${s.content}`).join('\n\n'),'answer'));extra.open=state.preferences.style==='full';p.append(extra);}}else p.append(E('p',a.answer));
 if(a.modelDraft)p.append(E('h3','模型生成的补充草稿'),E('div',a.modelDraft,'answer'),E('p','仅通过来源编号格式检查，未完成独立语义评审。以原文为准。','warning'));
 if(a.references?.length){const refs=E('div');refs.className='reference-panel';for(const ref of a.references){const box=E('div',undefined,'source evidence-reference');box.dataset.chunkId=ref.chunk_id;box.append(E('h3',`【来源${ref.id}】${ref.document_title} · ${ref.title}`),E('p',ref.source+(ref.page?' · 第'+ref.page+'页':'')+' · 版本'+ref.version,'muted'),E('blockquote',ref.quote,'answer original-quote'),E('small',ref.provenance_note),button('打开对应原文',()=>showDocument(ref.doc_id,ref.page)));refs.append(box);}p.append(details('参考文献与原文摘录（逐字可核对）',refs));p.lastChild.open=true;}
 const steps=E('div',undefined,'steps');(a.stages||[]).forEach(s=>steps.append(E('span',s.node+(s.status==='completed'?' ✓':' · '+s.status),'step')));p.append(steps,details('路由、改写与参数',jpre({routing:a.route,rewritten:a.rewritten,topK:a.topK,strategy:a.strategy,verification:a.verification_scope,elapsed_ms:a.elapsed_ms})));
 const actions=row();actions.append(button('复制回答',async()=>{await navigator.clipboard.writeText(a.answer);notice('已复制检索结果。')}),button('导出Trace',()=>downloadBlob(new Blob([JSON.stringify(a,null,2)],{type:'application/json'}),a.id+'.json')),button('记录反馈',()=>{last=a;mount('loop')}));if(a.sources?.length)actions.append(button('可选：调用部署者的模型',()=>modelPrompt(a)));p.append(actions);target.append(p);
 if(a.tool){const t=panel('同一工作流的工具输出');t.append(E('p','实际执行JavaScript函数；使用原包的模拟数据和默认参数。','muted'),table(a.tool.rows||[]),details('完整工具结果',jpre(a.tool)),button('调整参数/导出文件',()=>{selectedFlow=a.flow;mount('tools')}));target.append(t)}
 if(a.sources?.length){const s=panel('来源与完整资料');a.sources.forEach((x,i)=>{const item=E('div',undefined,'source'),r=row();r.append(E('span',`【来源${i+1}】${x.title}`,'source-title'),button('查看完整资料',()=>showDocument(x.doc_id,x.page)));item.append(r,E('small',`${x.source} · 片段 ${x.id} · 词项分数 ${x.score.toFixed(2)}`));s.append(item)});target.append(s)}
}
function modelPrompt(a){const p=E('div');p.append(E('p','仅在部署者配置了模型和访问码时可用。确认后将当前问题和来源发送到本站 /api/answer，再交给部署者配置的模型。默认不会发送。','warning'));const code=field('password','','model-code');code.placeholder='部署者提供的访问码（不保存）';const consent=field('checkbox','','model-consent'),out=E('div');p.append(code,label('同意发送当前问题及来源片段',consent),button('确认并生成',async b=>{if(!consent.checked)throw Error('请确认材料发送许可');b.disabled=true;try{const r=await fetch('/api/answer',{method:'POST',headers:{'Content-Type':'application/json','X-Access-Code':code.value},body:JSON.stringify({question:a.query,sources:a.sources.slice(0,5).map((s,i)=>({id:i+1,title:s.title,content:s.content})),consent:true})});let j;try{j=await r.json()}catch{throw Error('这个静态预览未配置模型API。分词检索仍然可用。')}if(!r.ok)throw Error(j.error||'模型服务未就绪');a.modelDraft=j.answer;a.model_meta=j;await save();out.replaceChildren(E('p',j.answer,'answer'));if($('ask-result'))renderAnswer(a,$('ask-result'));}catch(e){out.replaceChildren(E('p',e.message,'warning'));}finally{b.disabled=false}},'primary'),out);modal('可选模型增强',p);}
function showLibrary(){const p=panel('上传到当前浏览器'),r=row(),f=field('file','','upload-file');f.multiple=true;f.accept='.pdf,.docx,.txt,.md,.csv,.json,.jsonl,.zip';const select=flowSelect('upload-flow'),sensitivity=E('select');sensitivity.id='upload-sensitivity';[['public','公开'],['internal','内部'],['sensitive','敏感']].forEach(([v,t])=>sensitivity.append(new Option(t,v)));r.append(select,f,label('上传者标记',sensitivity));
 const progress=E('p','支持原生PDF、Word、文本、CSV、分页JSON及V4切片ZIP。单文件40MB；不自动OCR。','muted');
 p.append(E('p','文件在本地解析，不上传服务器，不共享给其他访客。本地启用不等于企业审核发布。公网预览只用公开或模拟材料。','warning'),r,button('解析并加入待审核',async b=>{if(!f.files.length)throw Error('先选择文件');b.disabled=true;try{for(const file of f.files){progress.textContent='正在解析 '+file.name;const docs=await parseFile(file,select.value,s=>progress.textContent=file.name+' · '+s);for(const d of docs){if(state.docs.some(x=>x.id===d.id)){log('Duplicate',{file:file.name});continue}const flags=d.chunks.some(c=>/身份证|银行账号|内部机密|客户姓名/.test(c.content));state.docs.push({...d,uploaded_at:now(),sensitivity:sensitivity.value,sensitivity_hint:flags?'正文命中敏感词，请人工复核':'规则未命中不代表没有敏感内容'});log('Parse',{id:d.id,chunks:d.chunks.length})}}await save();refreshIndex();mount('library');notice('解析完成。预览后点击“本地启用”，再进行问答。')}finally{b.disabled=false}},'primary'),progress);wrap.append(p);
 const list=panel('资料目录'),filter=field('search','','library-filter');filter.className='searchbox';filter.placeholder='搜索标题、来源或正文；含停用和待审资料';const items=E('div');list.append(filter,items);wrap.append(list);
 const draw=()=>{items.replaceChildren();const text=filter.value.trim().toLowerCase();const docs=[...state.docs,...seed.map(s=>({...s,id:s.doc_id,builtin:true,chunks:[s]}))].filter(d=>(d.title+' '+d.chunks.map(x=>x.content).join(' ')).toLowerCase().includes(text));items.append(E('p',`显示${docs.length}份资料；本地上传${state.docs.length}份。内置56主题提要，不是115页笔记全文。`,'muted'));
 for(const d of docs){const item=E('div',undefined,'source'),r=row();r.append(E('strong',d.title),E('span',(d.builtin?'内置 · ':'')+d.status+' · '+d.chunks.length+'片'+(d.sensitivity?' · '+d.sensitivity:''),'badge'),button('原文/切片',()=>showDocument(d.id)));
 if(!d.builtin)r.append(button(d.status==='active'?'本地停用':'本地启用',async()=>{if(d.status!=='active'&&!confirm('本地审核演示：已查看资料、来源与敏感标记？此操作不构成两人审核，仅启用到本浏览器。'))return;d.status=d.status==='active'?'archived':'active';d.review={scope:'single_browser_demo',at:now()};log('LocalReview',{id:d.id,status:d.status});await save();refreshIndex();draw()}),button('删除',async()=>{if(!confirm('删除此份本地资料？'))return;state.docs=state.docs.filter(x=>x.id!==d.id);await save();refreshIndex();draw()},'danger'));
 item.append(r,E('small',`${FLOWS[d.flow]?.[0]||'全局指南'} · ${d.parser||'文本'}${d.blank_pages?.length?' · '+d.blank_pages.length+'页未取得文字':''}`));if(d.sensitivity_hint)item.append(E('p',d.sensitivity_hint,'muted'));items.append(item)}};filter.oninput=draw;draw();
}
function showTools(){const p=panel('可执行业务工具'),s=flowSelect('tool-flow');for(const o of [...s.options])if(!DEFAULTS[o.value])o.remove();s.value=DEFAULTS[selectedFlow]?selectedFlow:'issuance';const params=E('textarea');params.id='tool-params';params.style.minHeight='145px';const output=E('div');output.id='tool-output';let result=null;
 s.onchange=()=>{params.value=JSON.stringify(DEFAULTS[s.value],null,2);selectedFlow=s.value};s.onchange();const run=button('执行工具',()=>{result=execute(s.value,JSON.parse(params.value),fixtures);output.replaceChildren(E('p',result.note||'仅供模拟与人工复核。','warning'),table(result.rows||[]),details('原始结构化结果',jpre(result)));log('Tool',{name:s.value,at:now()});save()},'primary');run.id='tool-run';
 p.append(E('p','对应原包8类工具入口。浏览器实际计算，不执行真实付款、冻结或发信。','muted'),s,params,run);const exports=row();
 exports.append(button('CSV导出',()=>{if(!result)throw Error('先执行工具');downloadBlob(new Blob([csvText(result.rows||[result])],{type:'text/csv;charset=utf-8'}),'jinshu-'+s.value+'.csv')}),button('JSON导出',()=>{if(!result)throw Error('先执行工具');downloadBlob(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),'jinshu-'+s.value+'.json')}),button('Word草稿',async()=>{if(!result)throw Error('先执行工具');const text=(result.synthetic?'模拟材料':'用户输入试算材料')+'，须人工复核。\n'+JSON.stringify(result.material_preview||{})+'\n'+(result.rows||[]).map(r=>Object.entries(r).map(([k,v])=>k+'：'+v).join('；')).join('\n');downloadBlob(await wordBlob(FLOWS[s.value][0],text),'金枢-'+s.value+'-草稿.docx')}));p.append(exports);
 const csv=field('file','','tool-csv');csv.accept='.csv';csv.onchange=()=>guard(async()=>{if(!csv.files.length)return;const rows=parseCSV(await csv.files[0].text());s.value='weekly_report';params.value=JSON.stringify({rows},null,2);notice(`已将CSV的${rows.length}行放入周报参数。点击执行进行质检。`)});p.append(details('用自己的周报CSV替换输入',label('选择CSV（不上传服务器）',csv)));wrap.append(p,output);
}
function showTraces(){const p=panel('实际执行记录');p.append(E('p','来自这个浏览器的真实函数执行，只保留最近80次问答。','muted'));for(const a of [...state.traces].reverse()){const r=row();r.append(E('span',a.query),E('small',a.at),button('查看',()=>{last=a;mount('ask')}),button('Trace JSON',()=>modal(a.id,jpre(a))));p.append(r)}if(!state.traces.length)p.append(E('div','先进行一次问答。','empty'));wrap.append(p);}
function showLoop(){const overview=panel('反馈如何改变下一轮执行'),bar=E('div',undefined,'steps');['Execute','Observe','Reflect','Adapt','Replay','启用 / 回滚'].forEach(n=>bar.append(E('span',n,'step')));overview.append(bar,E('p',`本地Trace ${state.traces.length} 条 · 反馈 ${state.feedback.length} 条 · 候选 ${state.candidates.length} 个 · 启用 ${state.candidates.filter(c=>c.status==='active').length} 个`,'muted'));wrap.append(overview);
 const p=panel('Observe · 记录反馈'),target=last||state.traces.at(-1);p.append(E('p',target?'当前任务：'+target.query:'请先执行任务。','muted'));const category=E('select');[['retrieval','检索没找到'],['intent','任务路由不对'],['generation','整理或答案有问题'],['knowledge_gap','资料库缺少知识']].forEach(([v,t])=>category.append(new Option(t,v)));category.id='feedback-category';const terms=field('text','','feedback-terms');terms.placeholder='期望补充的检索词';const note=E('textarea');note.id='feedback-note';note.placeholder='具体哪里不对？';
 p.append(category,terms,note,button('保存本次反馈',async()=>{if(!target?.flow)throw Error('先执行一个明确工作流');state.feedback.push({id:crypto.randomUUID(),trace_id:target.id,flow:target.flow,category:category.value,terms:terms.value.slice(0,100),note:note.value.slice(0,1000),at:now()});log('Observe',{trace_id:target.id});await save();notice('反馈已保存。下一步可生成受限候选。')},'primary'));wrap.append(p);
 const c=panel('Reflect → Adapt → Replay → 本地启用 / 回滚');c.append(E('p','以用户选择的归因和规则生成候选，实际回放历史检索。没有调用反思模型或改模型权重；本地启用不等于多用户灰度。','warning'),button('生成候选并回放',async()=>{const x=propose(state.feedback);if(x.cause==='knowledge_gap'){state.tickets.push({id:x.id,status:'needs_document',flow:x.flow,at:now()});await save();notice('已形成知识缺口待办，不以改top-k代替补资料。');return;}x.replay=replayCandidate(x,state.traces,activeRows());state.candidates.push(x);log('Replay',{id:x.id,passed:x.replay.passed});await save();mount('loop')}));
 for(const x of [...state.candidates].reverse()){const box=E('div',undefined,'source'),r=row();r.append(E('strong',FLOWS[x.flow]?.[0]||x.flow),E('span',x.status+' · top-k '+x.topK,'badge'),button('本地启用',async()=>{if(!x.replay.passed)throw Error('来源保留回放未通过');state.candidates.filter(y=>y.flow===x.flow&&y.status==='active').forEach(y=>y.status='replaced');x.status='active';log('DeployLocal',{id:x.id});await save();mount('loop');notice('候选对本浏览器下一轮同工作流生效。')}),button('回滚稳定基线',async()=>{x.status='rolled_back';log('Rollback',{id:x.id});await save();mount('loop');notice('已回滚；下一轮top-k=5，不改变资料或计算函数。')}));box.append(r,details('候选与配对回放',jpre(x)));c.append(box)}c.append(details('知识缺口待办',jpre(state.tickets)));wrap.append(c);
}
function showMemory(){const p=panel('一个事实来源区 + 五类记忆视图');p.append(E('p','同一浏览器的逻辑分区，不是Redis/Mongo服务。清除网站数据会删除它们，不同步到其他设备。','warning'));const style=E('select');style.append(new Option('完整依据','full'),new Option('简短优先','brief'));style.value=state.preferences.style||'brief';const consent=field('checkbox','','pref-consent');p.append(style,label('同意记录回答详略偏好',consent),button('保存偏好',async()=>{if(!consent.checked)throw Error('需要明确同意');state.preferences={style:style.value,at:now()};await save();notice('偏好已保存，下轮按选择展开相关依据。')}),button('清除偏好',async()=>{state.preferences={};await save();mount('memory')}));wrap.append(p);
 for(const[name,data]of [['工作记忆',{lastQuestion:state.lastQuestion,lastFlow:state.lastFlow,session:state.session}],['情景记忆（本地事件）',state.events.slice(-30)],['用户语义记忆（仅同意的偏好）',state.preferences],['组织知识（源绑定示意）',seed.filter(x=>x.flow==='service').map(x=>({doc_id:x.doc_id,version:x.version,source:x.source,status:x.status}))],['程序性记忆',state.candidates]]){const v=panel(name);v.append(jpre(data));wrap.append(v)}
}
const EVAL=[['商业银行的四个职能是什么？','finance_learning','learn-014'],['支付中介和信用中介的区别','finance_learning','learn-015'],['解释购买力平价','finance_learning','learn-007'],['什么是货币乘数？','finance_learning','learn-041'],['直接融资和间接融资','finance_learning','learn-025'],['交易预防投机动机','finance_learning','learn-036'],['什么是最后贷款人','finance_learning','learn-019'],['通货膨胀和货币幻觉','finance_learning','learn-044'],['期限结构三种理论','finance_learning','learn-050'],['道德风险和逆向选择','finance_learning','learn-051'],['发行排期遇非工作日顺延','issuance','sim-calendar'],['周报数字清洗','weekly_report','sim-weekly'],['开户字段决策时点','onboarding','sim-onboarding'],['案件邮件核查','kep','sim-kep'],['特征计数success','strategy','sim-feature'],['客服转人工','service','sim-service']];
export function runEvaluation(rows){const ix=new Index(rows);return EVAL.map(([query,flow,id])=>{const hits=ix.search(query,{flow,limit:5}),r=route(query,ix);return{query,flow,route:r.flow,route_match:r.flow===flow,gold:id,retrieved:hits.map(h=>h.id),...metrics(hits.map(h=>h.id),[id])}})}
function showEval(){const p100=panel('100题：路由、依据和引用联合验收'),out100=E('div');p100.append(E('p','56概念题、20改写题、16业务题、2追问、2多源题、4无依据题。运行公开资料；这是开发验收，不是独立盲测。','warning'),button('运行100题带出处验收',async b=>{b.disabled=true;try{const {evaluate}=await import('./benchmarking.mjs');const response=await fetch('benchmark100.json');if(!response.ok)throw Error('评测标签尚未随构建部署');const result=evaluate(await response.json(),seed);out100.replaceChildren(jpre(result.summary),table(result.rows.map(r=>({题号:r.id,问题:r.question,通过:r.pass,路由:r.route,召回:r.retrieved_ids.join('、'),关键点覆盖:r.key_coverage,原文逐字校验:r.quote_verified}))),button('导出100题答案、原文与出处',()=>downloadBlob(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),'jinshu-100-actual-result.json')));}finally{b.disabled=false}},'primary'),out100);wrap.append(p100);
const p=panel('即时运行 · 轻量版回归题');p.append(E('p','16条自编开发检查题，各有一个预期来源ID，不是独立金融准确率。基线仅使用内置资料，不挪用原材料成绩。','warning'));const out=E('div');p.append(button('运行16题检查',()=>{const rows=runEvaluation(seed),summary={scope:'开发回归；单一预期来源，不是完备gold',n:rows.length,route_hits:rows.filter(x=>x.route_match).length,hit_at_5:rows.reduce((n,r)=>n+r.hit,0)/rows.length,mrr_at_5:rows.reduce((n,r)=>n+r.mrr,0)/rows.length,at:now()};out.replaceChildren(jpre(summary),table(rows.map(({retrieved,...r})=>r)),button('导出实际评测结果',()=>downloadBlob(new Blob([JSON.stringify({summary,rows},null,2)],{type:'application/json'}),'lite-evaluation.json')));log('Eval',summary);save()},'primary'),out);wrap.append(p);
 const compare=panel('与完整版本对应');compare.append(table([{模块:'分词 / BM25 / 路由',轻量版:'实际JS函数与开发回归',完整版:'服务检索 + 真实向量 / Reranker'},{模块:'生成与验证',轻量版:'原文组织；可选模型草稿',完整版:'模型生成 + 验证 / 降级'},{模块:'并发 / HPA',轻量版:'不实现，不伪造副本数',完整版:'部署配置，集群压测未执行'},{模块:'用户效果',轻量版:'本地体验记录',完整版:'需真实招募与独立评审'}]));wrap.append(compare);}
function showPilot(){const p=panel('任务体验记录');p.append(E('p','本浏览器记录，不自动汇总为真人试点。测试标记默认勾选；耗时由参与者填写。','warning'));const task=field('text','task-01','pilot-task'),secs=field('number','30','pilot-seconds'),phase=E('select');phase.id='pilot-phase';phase.append(new Option('人工查找','manual'),new Option('助手辅助','agent'));const done=field('checkbox','','pilot-done'),test=field('checkbox','','pilot-test'),consent=field('checkbox','','pilot-consent');test.checked=true;const r=row();r.append(label('任务',task),label('秒',secs),phase,label('任务完成',done),label('测试数据',test),label('同意记录',consent));p.append(r,button('保存体验',async()=>{if(!consent.checked)throw Error('请确认同意');const n=Number(secs.value);if(!Number.isFinite(n)||n<=0||n>86400)throw Error('无效耗时');if(phase.value==='agent'&&!last)throw Error('先执行问答');state.pilot.push({id:crypto.randomUUID(),task:task.value,seconds:n,phase:phase.value,completed:done.checked,is_test:test.checked,trace_id:phase.value==='agent'?last.id:null,at:now()});state.consent=true;await save();mount('pilot')},'primary'),button('导出体验记录',()=>downloadBlob(new Blob([JSON.stringify(state.pilot,null,2)],{type:'application/json'}),'pilot-local.json')),button('撤回并删除记录',async()=>{state.pilot=[];state.consent=false;await save();mount('pilot')}),table(state.pilot));wrap.append(p);}
function showGuide(){const p=panel('轻量版为什么能直接打开');p.append(E('p','浏览器建立词项倒排索引，中文分词加双字补充，BM25考虑词频饱和与文档长度。标题加权、术语别名和任务规则完成路由。没有语义Embedding，不把词项分数当模型置信概率。'),E('pre','资料 → 解析 / 分页 / 切片 → 本地审核开关 → 词项索引\n提问 → 规则路由 → 改写 → BM25 → 来源组织 → 引用检查\n反馈 → 规则候选 → 历史检索回放 → 本地启用 / 回滚\n可选：明确同意 → Vercel服务端模型接口 → 待复核草稿'),E('p','原文页面可完整展开。PDF仅提取原生文字，复杂表格需复核；扫描图片未OCR。分页JSON可导入全部学习笔记；V4切片ZIP可按文档导入，默认全部待审。','muted'));wrap.append(p);
 const d=panel('部署与完整版');d.append(E('p','Vercel导入仓库，Root Directory设为lite，Framework选Other，Build Command为npm run build，Output Directory为dist。默认不需数据库或模型密钥。本项目实际体验地址为 https://jinshu-workbench.vercel.app；原工程与网站发布仓库分别维护。'),E('p','完整部署使用根目录Docker Compose。本地审核、反馈、记忆与回放是可操作简化版，不等于服务端鉴权、Redis消息确认或分布式发布。'),button('打开项目与部署手册',()=>window.open('https://github.com/cxy-peter/jinshu-fintech-agent','_blank','noopener')));wrap.append(d);
 const data=panel('工作区管理');data.append(E('p',memoryOnly?'仅内存模式，刷新可能丢失。':'存储在本网站源下的IndexedDB，不是服务器。请导出备份。','warning'),button('导出完整工作区',()=>downloadBlob(new Blob([JSON.stringify(state)],{type:'application/json'}),'jinshu-workspace-private.json')),button('清空本浏览器数据',async()=>{if(!confirm('删除本地资料、反馈、策略、Trace和体验记录？'))return;state=fresh();last=null;if(db)await db.clear();refreshIndex();mount('guide');notice('本地数据已清空。')},'danger'));wrap.append(data);}
async function start(){state=fresh();try{db=await openStore();const old=await db.load('workspace');if(old?.schema===5)state={...fresh(),...old}}catch{memoryOnly=true}const responses=await Promise.all(['knowledge.json','fixtures.json'].map(x=>fetch(x)));if(responses.some(r=>!r.ok))throw Error('资料加载失败，请使用构建完成的站点。');[seed,fixtures]=await Promise.all(responses.map(r=>r.json()));refreshIndex();for(const[id,title]of TABS){const b=button(title,()=>mount(id));b.dataset.tab=id;$('nav').append(b)}mount('ask');window.jinshuTest={runEvaluation:()=>runEvaluation(seed),getState:()=>state,ask:(q,f)=>ask(q,f),execute:(n,p)=>execute(n,p,fixtures),index};if(location.hostname.endsWith('githack.com'))notice('第三方静态预览：只使用公开/模拟材料。私人资料在自己的Vercel域名或本机处理。','warning');}
guard(start);
