import {chunksFromPages} from './core.mjs';
import {hash} from './storage.mjs';
let zipper;
export async function zipLib(){if(globalThis.JSZip)return globalThis.JSZip;if(!zipper)zipper=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL('vendor/jszip.min.js',import.meta.url).href;s.onload=()=>resolve(globalThis.JSZip);s.onerror=()=>{zipper=null;reject(Error('ZIP组件未加载。请使用已构建网站；TXT/CSV不依赖此组件。'))};document.head.append(s)});return zipper}
function xmlText(xml,tag){const d=new DOMParser().parseFromString(xml,'application/xml');if(d.querySelector('parsererror'))throw Error('XML解析失败');return [...d.getElementsByTagName(tag)].map(x=>x.textContent).join('\n')}
export async function parseFile(file,flow,progress=()=>{}){
 if(file.size>40*1024*1024)throw Error('单文件限制40MB；大语料先转换为切片包');const bytes=await file.arrayBuffer(),digest=await hash(bytes),id='u-'+digest.slice(0,20),ext=file.name.toLowerCase().split('.').pop();let pages=[];
 if(ext==='pdf'){
  const pdfjs=await import('./vendor/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdf.worker.mjs',import.meta.url).href;
  const doc=await pdfjs.getDocument({data:new Uint8Array(bytes),isEvalSupported:false,useSystemFonts:true,cMapUrl:new URL('./vendor/cmaps/',import.meta.url).href,cMapPacked:true}).promise;
  if(doc.numPages>1500){await doc.destroy();throw Error('PDF超过1500页限制')}
  try{for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),t=await p.getTextContent();let text='',y=null;for(const s of t.items){if(!('str' in s))continue;const ny=s.transform?.[5];if(y!==null&&Math.abs(ny-y)>3)text+='\n';text+=s.str+(s.hasEOL?'\n':'');y=ny;}pages.push({page:i,text});progress(`${i}/${doc.numPages}页`);}}finally{await doc.destroy();}
 }else if(ext==='docx'){
  const Zip=await zipLib(),z=await Zip.loadAsync(bytes),entry=z.file('word/document.xml');if(!entry)throw Error('缺少Word正文');if(entry._data?.uncompressedSize>12000000)throw Error('正文过大');pages=[{page:1,text:xmlText(await entry.async('string'),'w:p')}];
 }else if(ext==='zip'||ext==='jsonl'){
  let raw;if(ext==='zip'){const Zip=await zipLib(),z=await Zip.loadAsync(bytes),entry=Object.values(z.files).find(x=>/(^|\/)chunks.jsonl$/.test(x.name));if(!entry)throw Error('仅支持含chunks.jsonl的V4/V5语料ZIP，不展开任意压缩包');if(entry._data?.uncompressedSize>80000000)throw Error('解压切片超过80MB');raw=await entry.async('string');}else raw=new TextDecoder().decode(bytes);
  if(raw.length>40000000)throw Error('切片文本超出长度限制');const lines=raw.split(/\r?\n/).filter(x=>x.trim());if(lines.length>25000)throw Error('最多25000个片段');const grouped=new Map();
  for(let i=0;i<lines.length;i++){let r;try{r=JSON.parse(lines[i])}catch{throw Error('第'+(i+1)+'行不是有效JSON')};if(typeof r.content!=='string'||r.content.length>50000)throw Error('切片缺少content或超过限制');const key=String(r.doc_id||'import');if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(r)}
  return [...grouped].map(([key,rs],n)=>{const did=id+'-'+n,title=String(rs[0].source_file||rs[0].title||key);const f=rs[0].source_kind==='research_reference'?'fund_research':flow;return{id:did,title,flow:f,sha256:digest,status:'pending_review',version:1,source:'本地导入（未外发）',pages:[],chunks:rs.map((r,i)=>({id:did+':'+i,doc_id:did,title,flow:f,source:'用户资料／'+title,page:r.metadata?.page||r.page||null,status:'pending_review',version:1,content:r.content,original_id:r._id,metadata:r.metadata})),blank_pages:[],parser:'existing_chunks'};});
 }else if(['txt','md','csv','json'].includes(ext)){const raw=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(ext==='json'){const obj=JSON.parse(raw);if(Array.isArray(obj.pages)){if(obj.pages.length>1500||obj.pages.some(p=>typeof p.text!=='string'))throw Error('无效的分页资料包');pages=obj.pages.map((p,i)=>({page:p.page||i+1,text:p.text}));}else pages=[{page:1,text:raw}];}else pages=[{page:1,text:raw}];}else throw Error('支持PDF、DOCX、TXT、MD、CSV、JSON、JSONL与切片ZIP；扫描件不自动OCR');
 const total=pages.reduce((n,p)=>n+p.text.length,0);if(total>10000000)throw Error('提取正文超过1000万字符');if(!total)throw Error('未取得原生文字；扫描件需要先转写，不会假装解析成功');const title=file.name;
 return[{id,title,flow,sha256:digest,status:'pending_review',version:1,source:'用户本地上传',pages,chunks:chunksFromPages(pages,{id,title,flow}),blank_pages:pages.filter(x=>!x.text.trim()).map(x=>x.page),parser:ext}];
}
export function parseCSV(text){const rows=[];let row=[],field='',quoted=false;text=text.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(x=>x!==''))rows.push(row);row=[];field=''}else field+=c;}if(quoted)throw Error('CSV引号不配对');row.push(field);if(row.some(x=>x!==''))rows.push(row);const headers=rows.shift();if(!headers||new Set(headers).size!==headers.length)throw Error('CSV表头缺失或重复');return rows.map((r,i)=>{if(r.length!==headers.length)throw Error('CSV第'+(i+2)+'行列数不一致');return Object.fromEntries(headers.map((h,j)=>[h,r[j]]))})}
export function csvText(rows){if(!rows.length)return '';const cols=Object.keys(rows[0]);const cell=v=>{let t=String(v??'');if(typeof v==='string'&&/^[=+@-]/.test(t.trimStart()))t="'"+t;return '"'+t.replace(/"/g,'""')+'"'};return '\uFEFF'+[cols,...rows.map(r=>cols.map(c=>typeof r[c]==='object'?JSON.stringify(r[c]):r[c]))].map(r=>r.map(cell).join(',')).join('\r\n')}
export async function wordBlob(title,text){const Zip=await zipLib(),z=new Zip(),esc=x=>x.replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]));z.file('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');z.file('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');z.file('word/document.xml','<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+[title,...text.split('\n')].map(s=>'<w:p><w:pPr><w:spacing w:after="140"/></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial" w:eastAsia="Microsoft YaHei"/><w:sz w:val="22"/></w:rPr><w:t xml:space="preserve">'+esc(s)+'</w:t></w:r></w:p>').join('')+'<w:sectPr/></w:body></w:document>');return z.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})}
