/** Read-only financial workflow examples, ported from jinshu/tools.py. All fixtures synthetic. */
export function num(x,percent=false){if(x===null||x===undefined||['','--','-','N/A'].includes(String(x).trim()))return null;let raw=String(x).trim();if(raw.includes(',')&&!/^[+-]?\d{1,3}(,\d{3})+(\.\d+)?%?$/.test(raw.replace(/^\((.*)\)$/,'-$1')))throw Error('千分位分组不合法，请核对原始数据：'+x);let t=raw.replaceAll(',','');if(/^\(.*\)$/.test(t))t='-'+t.slice(1,-1);let scale=1;if(t.endsWith('%')){if(!percent)throw Error('百分比不能用作金额');t=t.slice(0,-1);scale=100;}if(!/^[-+]?(\d+(\.\d*)?|\.\d+)$/.test(t))throw Error('无效数值：'+x);const n=Number(t)/scale;if(!Number.isFinite(n))throw Error('禁止非有限数');return n}
const day=s=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Error('日期应为YYYY-MM-DD');const d=new Date(s+'T00:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==s)throw Error('无效日期');return d};
const date=d=>d.toISOString().slice(0,10),plus=(d,n)=>new Date(+d+n*86400000),int=(x,def,min,max)=>{x=Number(x??def);if(!Number.isInteger(x)||x<min||x>max)throw Error('整数参数超出范围');return x};
export function execute(name,p={},data){let result;const note='模拟数据；只读预览，需人工复核，不执行真实业务。';
 if(name==='issuance'||name==='material_fill'){
 const cfg=data.calendar,start=day(p.start||'2026-09-25'),term=int(p.term_days,90,1,3650),freq=int(p.frequency_days,7,7,14),count=int(p.count,3,1,20);if(![7,14].includes(freq))throw Error('频率仅7或14天');
 const valid=d=>![0,6].includes(d.getUTCDay())&&!cfg.holidays.includes(date(d));const advance=d=>{while(!valid(d))d=plus(d,1);return d};
 const rows=Array.from({length:count},(_,i)=>{const planned=plus(start,i*freq),actual=advance(planned),maturity=advance(plus(actual,term));let close=plus(actual,-1);while(!valid(close))close=plus(close,-1);return{'批次':i+1,'拟成立日':date(planned),'成立日':date(actual),'募集结束日':date(close),'到期日':date(maturity),'实际自然日':(+maturity-actual)/86400000,'顺延':+planned!==+actual,'日历版本':cfg.version}});
 result={rows,material_preview:{标题:p.title||'模拟产品发行材料草稿',约定期限自然日:term,发行频率天:freq,日历版本:cfg.version},note:'仅使用SIM-CALENDAR-v1模拟营业日历。'+note};
 }else if(name==='weekly_report'){
 const seen=new Set(),issues=[];const rows=(p.rows||data.weekly_raw).map((r,i)=>{if(typeof r['登记编码']!=='string')throw Error('登记编码必须是字符串；请回原始资料核对前导零');if(!r['登记编码']||!r['数据日期'])throw Error('缺少登记编码或数据日期');const k=r['登记编码']+'|'+r['数据日期'];if(seen.has(k))throw Error('登记编码/日期重复：'+k);seen.add(k);const rate=num(r['区间收益率'],true);if(rate===null)issues.push({源行:i+2,字段:'区间收益率',状态:'保留缺失，未填零'});return{'登记编码':String(r['登记编码']),'名称':r['名称'],'规模万元':num(r['规模万元']),'区间收益率':rate,'数据日期':r['数据日期'],'源行':i+2}});result={rows,issues,note:'登记编码保留前导零；输入不覆盖。'+note};
 }else if(name==='wealth_benchmark'){
 const catalog=p.products||data.products,series=p.nav||data.nav,target=catalog.find(r=>r['产品编码']===(p.product||'SIM0001'));if(!target)throw Error('找不到目标产品');const peers=catalog.filter(r=>['投资性质','运作模式','风险等级','持有期限','代销渠道','币种'].every(k=>r[k]===target[k]));if(peers.length<2)throw Error('同口径可比样本不足');
 const start=p.start||'2026-06-01',end=p.end||'2026-08-30';day(start);day(end);if(start>=end)throw Error('观察日期倒置');
 const rows=peers.map(prod=>{const a=series.filter(r=>r['产品编码']===prod['产品编码']&&r['净值日期']>=start&&r['净值日期']<=end).sort((a,b)=>a['净值日期'].localeCompare(b['净值日期']));if(!a.length||a[0]['净值日期']!==start||a.at(-1)['净值日期']!==end)throw Error('缺少共同起止日净值');if(new Set(a.map(r=>r['净值日期'])).size!==a.length)throw Error('净值日期主键重复');const vs=a.map(r=>num(r['累计净值']));if(vs.some(v=>v===null||v<=0))throw Error('净值缺失或非正');let peak=vs[0],dd=0;for(const v of vs){peak=Math.max(v,peak);dd=Math.max(dd,1-v/peak)}return{'产品编码':prod['产品编码'],'产品全称':prod['产品全称'],'区间收益率':vs.at(-1)/vs[0]-1,'最大回撤':dd,'起始日':start,'截止日':end}});
 const vs=rows.map(r=>r['区间收益率']).sort((a,b)=>a-b),tr=rows.find(r=>r['产品编码']===target['产品编码'])['区间收益率'];result={rows,summary:{同口径样本数:rows.length,样本收益中位数:(vs[Math.floor((vs.length-1)/2)]+vs[Math.floor(vs.length/2)])/2,严格低于目标的样本比例:vs.filter(x=>x<tr).length/vs.length},note:'无分红的合成净值；非全市场排名，JS浮点展示不作资金结算。'+note};
 }else if(name==='onboarding'){
 const stage=int(p.decision_stage,1,1,4);result={rows:data.onboarding.map(r=>({...r,available_now:Number(r.available_stage)<=stage,待确认:Number(r.available_stage)<=stage?'核对用途和授权':'尚未采集，不允许使用未来信息'})),decision_stage:stage,note};
 }else if(name==='kep'){
 const normalize=s=>String(s).trim().replaceAll('/','-');result={rows:data.cases.map(c=>{let via='case_no',f=data.mails.filter(m=>normalize(m.case_no)===normalize(c.case_no));if(!f.length){via='reference_no';f=data.mails.filter(m=>c.reference_no&&m.reference_no===c.reference_no)}return{case_id:c.case_id,status:f.length===1?'found_sent_record':f.length?'ambiguous':'not_found_needs_review',match_key:via,evidence_ids:f.map(x=>x.message_id),delivery:f.length===1?f[0].delivery:'unconfirmed'}}),note:'未找到不等于漏回复；发送不等于送达；不发邮件。'};
 }else if(name==='strategy'){
 const feature=p.feature||'successful_deposit_count_7d',event=p.event||'FiatDeposit',r=data.features.find(x=>x.name===feature&&x.event===event);if(!r)throw Error('未登记特征或事件不匹配');result={rows:[r],candidate:{feature,event,operator:'>=',threshold:int(p.threshold,5,1,1000000),status:'disabled',approval:'required'},note:'仅生成禁用候选，不连接风控平台，不调整真实账户。'};
 }else if(name==='statements'){
 const r=data.statements.find(r=>Number(r.year)===Number(p.year||2025));if(!r)throw Error('无该年度模拟数据');const required=['assets','liabilities','equity','cfo','cfi','cff','fx','net_cash_change','opening_cash','ending_cash'];const missing=required.filter(k=>num(r[k])===null);if(missing.length)return{tool:name,synthetic:true,rows:[r],checks:null,passed:false,status:'incomplete_needs_review',missing_fields:missing,note:'勾稽必需字段缺失；不按0计算，须人工补充。'};const v=Object.fromEntries(Object.entries(r).filter(([k])=>!['unit','scope','synthetic'].includes(k)).map(([k,v])=>[k,num(v)]));const checks={资产负债:v.assets-v.liabilities-v.equity,现金净变动:v.net_cash_change-v.cfo-v.cfi-v.cff-v.fx,期末现金:v.ending_cash-v.opening_cash-v.net_cash_change};result={rows:[r],checks,passed:Object.values(checks).every(x=>Math.abs(x)<1e-8),note};
 }else throw Error('该入口为知识问答，不是计算工具');return{tool:name,synthetic:!(p.rows||p.products||p.nav),...result};
}
export const DEFAULTS={wealth_benchmark:{product:'SIM0001',start:'2026-06-01',end:'2026-08-30'},issuance:{start:'2026-09-25',term_days:90,frequency_days:7,count:3},material_fill:{title:'模拟稳健理财发行材料',start:'2026-09-25',term_days:90,frequency_days:7,count:3},weekly_report:{},onboarding:{decision_stage:1},kep:{},strategy:{feature:'successful_deposit_count_7d',event:'FiatDeposit',threshold:5},statements:{year:2025}};
