/* Presentation and HTTP calls only. No client retrieval, business formulas or policy approval. */
'use strict';
const $=id=>document.getElementById(id),E=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let token='',user=null,cat=null,session='',last=null,epoch=0,active='ask';
const pages={ask:'资料问答',tasks:'业务任务',docs:'知识维护',memory:'记忆与偏好',loop:'反馈与策略',traces:'执行记录',ops:'异常与工单',pilot:'验收与体验',settings:'服务与配置'};
const flowTool={wealth_benchmark:1,issuance:1,weekly_report:1,onboarding:1,kep:1,strategy:1,statements:1,material_fill:1};
const labels={start:'起始/拟成立日',end:'观察截止日',product:'产品编码',product_name:'产品名称',term_days:'期限（自然日）',frequency_days:'发行间隔（7或14天）',count:'批次数',decision_stage:'决策阶段（1–4）',year:'报表年度',feature:'特征名称',event:'事件名称',threshold:'候选阈值'};
const defaults={start:'2026-09-25',end:'2026-08-30',product:'SIM0001',product_name:'示例产品',term_days:90,frequency_days:7,count:3,decision_stage:1,year:2025,feature:'successful_deposit_count_7d',event:'FiatDeposit',threshold:5};
function notice(t){$('notice').textContent=t||'';}
function button(text,fn,cls){const b=E('button',text,cls);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn(b)}catch(e){notice(e.message)}finally{b.disabled=false}};return b;}
function card(title){const c=E('section',undefined,'card');if(title)c.append(E('h2',title));return c;}
function details(title,value){const d=E('details');d.append(E('summary',title),value instanceof Node?value:E('pre',JSON.stringify(value,null,2)));return d;}
function table(rows){if(!Array.isArray(rows)||!rows.length)return E('p','暂无记录','small');const w=E('div',undefined,'table-wrap'),t=E('table'),head=E('tr'),keys=[...new Set(rows.flatMap(Object.keys))];keys.forEach(k=>head.append(E('th',k)));t.append(head);rows.forEach(r=>{const tr=E('tr');keys.forEach(k=>tr.append(E('td',typeof r[k]==='object'?JSON.stringify(r[k]):String(r[k]??''))));t.append(tr)});w.append(t);return w;}
function field(name,type='text',value=''){const l=E('label',name),i=E('input');i.type=type;if(type==='checkbox')i.checked=!!value;else i.value=value;l.append(i);return [l,i];}
function select(items){const s=E('select');for(const [value,name]of items){const o=E('option',name);o.value=value;s.append(o)}return s;}
async function api(path,method='GET',data,raw=false){const headers=token?{Authorization:'Bearer '+token}:{};let body;if(data instanceof FormData)body=data;else if(data!==undefined){headers['Content-Type']='application/json';body=JSON.stringify(data)}const res=await fetch('/api/'+path,{method,headers,body,cache:'no-store'});if(!res.ok){let j;try{j=await res.json()}catch{};if(res.status===401){token='';user=null;$('login-panel').hidden=false;}const d=j?.detail;throw Error(typeof d==='string'?d:d?.code==='configuration_required'?'完整后端尚缺云端配置，请查看“服务与配置”。':JSON.stringify(d||j||res.status));}return raw?res:res.json();}
function download(blob,name){const u=URL.createObjectURL(blob),a=E('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),2000);}
function authNeeded(c){if(token)return false;c.append(E('p','登录后使用服务器中的真实工作区。未登录不会读取其他人的资料，也不会返回演示答案。','warn'));return true;}
async function status(){const s=await api('status');$('connection').textContent=s.configured?(s.connected?'完整后端已初始化':'配置存在，待验证连接'):'云端配置待完成';$('setup-status').replaceChildren();if(!s.configured)$('setup-status').append(E('p','当前尚不能完成真实问答。需要部署者在Vercel的环境变量中配置数据服务和模型，不要在聊天或GitHub里公开密钥。','warn'),details('缺少/无效的配置名称',s.required_configuration));return s;}
$('login-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const d=await api('login','POST',{username:$('username').value,password:$('password').value});token=d.token;user=d.user;$('password').value='';cat=await api('catalog');$('identity').textContent=user.name||user.id;$('logout').hidden=false;$('login-panel').hidden=true;notice('已登录。同一浏览器刷新后需重新登录；服务器数据仍保留。');await status();await mount(active);}catch(e){notice(e.message)}finally{b.disabled=false}};
$('logout').onclick=()=>{token='';user=null;cat=null;session='';last=null;epoch++;$('identity').textContent='未登录';$('logout').hidden=true;$('login-panel').hidden=false;mount('settings');};
for(const[id,name]of Object.entries(pages))$('nav').append(button(name,()=>mount(id)));
async function mount(id){active=id;epoch++;$('content').replaceChildren();[...$('nav').children].forEach((b,i)=>b.setAttribute('aria-current',Object.keys(pages)[i]===id));try{await renderers[id]()}catch(e){notice(e.message)}}
function wrap(title){const c=card(title);$('content').append(c);return c;}
function flowSelect(){return select(Object.entries(cat?.workflows||{}).map(([k,w])=>[k,w.name]));}
async function ask(){const c=wrap('先查依据，再核对结论');if(authNeeded(c))return;const flow=flowSelect();flow.value=cat.workflows.finance_learning?'finance_learning':flow.value;const q=E('textarea');q.placeholder='描述你的问题；日期、产品编码、否定条件请明确。';const[l,consent]=field('同意将本次问题和已审核允许外发的片段发送至配置模型','checkbox');const out=E('div');c.append(flow,q,l,E('p','资料须先上传并由另一名审核账号发布。计算请前往业务任务页，不会自动使用示例数据。','small'),button('提交问答',async()=>{const current=++epoch;const a=await api('ask','POST',{query:q.value,workflow:flow.value,session_id:session,allow_external:consent.checked});if(current!==epoch)return;session=a.session_id;last=a;renderAnswer(a,out);},'primary'),button('新会话',()=>{epoch++;session='';last=null;out.replaceChildren();}),out);if(last)renderAnswer(last,out);}
function renderAnswer(a,out){out.replaceChildren();out.append(E('h3','回答'),E('p',a.answer||'没有获得回答','answer'));const x=a.execution||{};out.append(E('p','模式：'+(x.answer_mode||'查看执行记录')+'；验证：'+(a.verification?.passed?'通过本次验证':'未通过/无依据'),'small'));const sources=E('div');for(const ref of a.citations||[])sources.append(details(ref.title||ref.doc_title||ref.doc_id,E('p',ref.snippet||JSON.stringify(ref),'answer')));out.append(details('来源与原文',sources),details('实际模型调用与执行记录',{trace_id:a.trace_id,model_calls:x.model_calls||[],execution:x}));if(flowTool[a.workflow])out.append(button('前往工具任务，确认输入再计算',()=>mount('tasks')));const f=E('div',undefined,'row'),types=select([['retrieval','检索问题'],['intent','理解问题'],['generation','表达/生成'],['knowledge_gap','缺少资料']]),n=E('input');n.placeholder='可选脱敏说明';f.append(types,n);for(const[name,signal]of [['已解决','up'],['未解决','down']])f.append(button(name,async()=>{await api('feedback','POST',{trace_id:a.trace_id,signal,category:types.value,note:n.value});notice('已更新同一回答的反馈。')}));out.append(f);}
async function taskView(){const c=wrap('数据输入 → 执行 → 复核 → 导出');if(authNeeded(c))return;const catalog=await api('tool-catalog'),sel=select(catalog.map(x=>[x.tool,x.name])),fields=E('div',undefined,'grid'),sources=E('textarea'),info=E('p','','small'),output=E('div'),existing=await api('tasks');sources.placeholder='例如 {"weekly_raw.csv": [{...}]}';let inputs={},activeTask=null,dirty=false;const[l,examples]=field('明确使用项目合成示例（不是本人的业务数据）','checkbox');
 function draw(){inputs={};fields.replaceChildren();const item=catalog.find(x=>x.tool===sel.value);info.textContent='本工具需要：'+item.required_sources.join('、')+'。执行与复核都在服务器完成。';for(const key of item.required_params){const numeric=['term_days','frequency_days','count','decision_stage','year','threshold'].includes(key);const[label,input]=field(labels[key]||key,numeric?'number':key==='start'||key==='end'?'date':'text','');inputs[key]=input;fields.append(label)}activeTask=null;dirty=false;output.replaceChildren();}
 function payload(){const values={};for(const[k,i]of Object.entries(inputs))if(i.value!=='')values[k]=i.type==='number'?Number(i.value):i.value;return{tool:sel.value,values,sources:examples.checked?null:JSON.parse(sources.value||'null'),use_examples:examples.checked};}
 function markDirty(){dirty=true;output.replaceChildren(E('p','输入已修改但尚未保存。旧结果不能确认或导出，请先保存并重新执行。','warn'));}
 sources.addEventListener('input',markDirty);examples.addEventListener('change',markDirty);fields.addEventListener('input',markDirty);
 async function saveInput(){const p=payload(),captured=JSON.stringify(p);activeTask=activeTask?await api('tasks/'+activeTask._id,'PUT',{...p,revision:activeTask.revision}):await api('tasks','POST',p);dirty=JSON.stringify(payload())!==captured;drawResult();}
 function drawResult(){if(dirty)return markDirty();output.replaceChildren();if(!activeTask)return;const t=activeTask;output.append(E('h3','任务 '+t._id.slice(0,8)+' · 版本 '+t.revision),E('p','状态：'+t.status));if(t.error)output.append(E('p',t.error,'warn'));if(t.result)output.append(E('p',t.result.input_mode==='synthetic_example'?'合成示例计算；不代表真实业务结果。':'本次用户输入计算；仍需核对口径。','warn'),table(t.result.result.rows||[]),details('完整计算、异常与来源哈希',t.result));if(t.status==='needs_review')output.append(button('我已核对当前输入、异常和结果',async()=>{if(!confirm('确认的是当前结果版本，不代表批准真实业务操作。继续？'))return;activeTask=await api('tasks/'+t._id+'/approve','POST',{revision:t.revision});drawResult();},'primary'));if(t.status==='approved')for(const fmt of ['json','csv','docx'])output.append(button('导出 '+fmt.toUpperCase(),async()=>{const r=await api(`tasks/${t._id}/export?revision=${t.revision}&format=${fmt}`,'GET',undefined,true);download(await r.blob(),`jinshu-${t._id}.${fmt}`);}));}
 const history=select([['','选择历史任务'],...existing.map(x=>[x._id,x.tool+' / '+x.status+' / v'+x.revision])]);history.onchange=async()=>{if(!history.value)return;try{const t=await api('tasks/'+history.value);sel.value=t.tool;draw();activeTask=t;for(const[k,i]of Object.entries(inputs))i.value=t.values[k]??'';sources.value=JSON.stringify(t.sources||{},null,2);examples.checked=t.use_examples;dirty=false;drawResult()}catch(e){notice(e.message)}};
 sel.onchange=draw;c.append(history,sel,fields,l,info,sources,button('填入合成示例参数',async()=>{const data=await api('tool-examples/'+sel.value);sources.value=JSON.stringify(data.sources,null,2);examples.checked=true;for(const[k,i]of Object.entries(inputs))i.value=(k==='start'&&sel.value==='wealth_benchmark')?'2026-06-01':defaults[k]??'';markDirty();}),button('保存新输入 / 使旧确认失效',saveInput),button('执行已保存版本',async()=>{if(!activeTask)await saveInput();else if(JSON.stringify(payload())!==JSON.stringify({tool:activeTask.tool,values:activeTask.values,sources:activeTask.sources,use_examples:activeTask.use_examples}))await saveInput();const captured=JSON.stringify(payload());activeTask=await api('tasks/'+activeTask._id+'/execute','POST',{revision:activeTask.revision});dirty=JSON.stringify(payload())!==captured;drawResult();},'primary'),output);draw();}
async function docs(){const c=wrap('知识维护与独立审核');if(authNeeded(c))return;const dept=select(Object.entries(cat.departments)),kind=select([['institutional_document','机构制度'],['learning_reference','学习参考'],['research_reference','研究参考'],['synthetic','合成示例']]);const[fl,f]=field('选择资料（3.5MB以内）','file');f.accept='.pdf,.docx,.txt,.md,.csv,.json,.zip';const[tl,topic]=field('主题标识（英文数字）'),[vl,version]=field('版本','number',1),sensitivity=select([['internal','内部'],['public','公开'],['restricted','受限'],['sensitive','敏感']]);c.append(E('p','原生PDF、Word、文本、CSV、分页JSON与JSON ZIP。不会自动OCR；上传不等于发布，原文送模型需另行授权。','small'),fl,tl,vl,dept,kind,sensitivity,button('上传为待审资料',async()=>{if(!f.files[0])throw Error('请选择文件');const d=new FormData();d.set('file',f.files[0]);d.set('dept_id',dept.value);d.set('topic',topic.value);d.set('version',version.value);d.set('source_kind',kind.value);d.set('manual_sensitivity',sensitivity.value);await api('documents/upload','POST',d);await mount('docs');},'primary'));for(const d of await api('documents')){const box=card(d.title+' / v'+d.version);box.append(E('p',d.status+' · '+d.source_kind+' · '+d.sensitivity+' · '+d.chunk_count+'片段','small'),button('查看提取原文',async()=>box.append(details('原文与页码',await api('documents/'+d._id+'/chunks')))));if(user.role==='admin'&&d.status==='pending_review'){const[l,allow]=field('允许审核通过的非敏感材料用于外部Embedding与模型','checkbox'),[rl,reason]=field('复核理由');box.append(l,rl,button('以当前账号审核发布',async()=>{await api('documents/'+d._id+'/review','POST',{final_sensitivity:d.sensitivity,allowed_depts:[d.dept_id],external_allowed:allow.checked,reason:reason.value});await mount('docs');},'primary'),button('退回',async()=>{await api('documents/'+d._id+'/reject','POST',{reason:reason.value});await mount('docs');}));}if(user.role==='admin'&&d.status==='active')box.append(button('停用资料',async()=>{const reason=prompt('停用理由');if(reason){await api('documents/'+d._id+'/archive','POST',{reason});await mount('docs');}},'danger'));$('content').append(box);}}
async function memory(){const c=wrap('会话信息不是事实依据');if(authNeeded(c))return;c.append(E('p','工作、情景、用户偏好、组织知识与程序策略分别管理。正式依据仍须回到活动文档。'));if(session)c.append(details('当前会话的五类记忆',await api('memory/'+session)));else c.append(E('p','先完成一次问答即可查看当前会话记忆。'));const[kl,key]=field('偏好名称'),[vl,value]=field('偏好值'),[cl,consent]=field('同意保存本条低敏偏好','checkbox');c.append(kl,vl,cl,button('保存偏好',async()=>{await api('memory/preferences','POST',{key:key.value,value:value.value,consent:consent.checked});await mount('memory');}));if(session){const m=await api('memory/'+session);for(const p of m.user_semantic||[])c.append(button('删除偏好 '+(p.key||p._id),async()=>{await api('memory/preferences/'+p._id,'DELETE');await mount('memory');}));}}
async function loop(){const c=wrap('反馈 → 候选 → 回放 → 审核 → 灰度 / 回滚');if(authNeeded(c))return;c.append(E('p','本页调用完整服务Loop。外部模型模式默认不自动外传历史反馈，只提出受限规则候选；不修改模型权重。','small'));const data=await api('loop');c.append(button('将反馈加入Loop作业',async()=>{await api('loop/run','POST');notice('已入队，请执行一个批次并查看状态。');}),button('执行一个有界作业批次',async()=>{const r=await api('jobs/process','POST');notice(r.status);await mount('loop');}),details('作业与知识缺口',{jobs:data.jobs,gaps:data.knowledge_gaps}));for(const s of data.skills.filter(x=>x.status==='pending'||x.experiment_id)){const b=card(s.name);b.append(E('p',s.status),details('基线、候选和绑定证据',s));if(s.status==='pending')b.append(button('审核候选并进入5%灰度',async()=>{if(!confirm('已查看回放结果并确认发布？'))return;await api('skills/'+s._id+'/approve','POST');await mount('loop');}));if(s.status==='active')b.append(button('查看分组指标',async()=>b.append(details('指标（样本不足不扩量）',await api('skills/'+s._id+'/metrics')))),button('按门槛申请扩量',async()=>{await api('skills/'+s._id+'/promote','POST');await mount('loop');}),button('暂停 / 回滚',async()=>{await api('operations/rollback','POST',{skill_id:s._id,reason:'人工复核后暂停'});await mount('loop');},'danger'));$('content').append(b);}c.append(details('全部策略、规则与Hook',data));}
async function traces(){const c=wrap('实际执行记录');if(authNeeded(c))return;for(const t of await api('traces')){const b=card(t.query);b.append(E('p',t.answer,'answer'),details('来源、校验、模型调用、耗时和策略',t));c.append(b);}}
async function ops(){const c=wrap('异常与工单');if(authNeeded(c))return;const note=E('textarea');note.placeholder='脱敏的待处理事项；当前不会向外部客服系统发送。';c.append(note,button('保存待提交工单',async()=>c.append(details('待提交记录',await api('tickets','POST',{summary:note.value})))));if(user.role==='admin')c.append(details('共享恢复状态与待办',await api('operations')));}
async function pilot(){const c=wrap('体验结果与评测边界');if(authNeeded(c))return;const[sl,seconds]=field('包含人工复核的实际耗时（秒）','number'),[tl,test]=field('这是测试数据，不计入真实用户效果','checkbox',true),[cl,consent]=field('同意保存本次体验记录','checkbox'),[dl,done]=field('任务已完成','checkbox'),rating=select([['3','3分'],['4','4分'],['5','5分'],['2','2分'],['1','1分']]);c.append(E('p','不要将HTTP200、检索非空或生成文件等同于业务完成。这里的成绩由参与者提交，不是独立质量标签。'),sl,tl,cl,dl,rating,button('保存本次体验',async()=>{if(!consent.checked||!last)throw Error('需要同意记录并先完成一次问答');await api('pilot/consent','POST',{consent:true});await api('pilot/result','POST',{task_id:last.trace_id,phase:'agent',trace_id:last.trace_id,seconds:Number(seconds.value),completed:done.checked,rating:Number(rating.value),note:'',is_test:test.checked});notice('已保存本次填写记录。');}),button('撤回并删除我的体验记录',async()=>{await api('pilot/withdraw','POST');notice('已撤回。');}));}
async function exportLegacy(){if(!indexedDB.databases)throw Error('浏览器不支持枚举旧数据，请使用原工作区导出备份');const dbs=await indexedDB.databases();if(!dbs.some(x=>x.name==='jinshu-lite-v5'))throw Error('当前域名/浏览器没有V7本地工作区');const data=await new Promise((resolve,reject)=>{const q=indexedDB.open('jinshu-lite-v5');q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result,r=db.transaction('state').objectStore('state').get('workspace');r.onsuccess=()=>{resolve(r.result);db.close()};r.onerror=()=>reject(r.error)}});if(!data)throw Error('旧工作区为空');download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'jinshu-v7-local-backup.json');notice('仅保存到本机，未上传或清除旧数据。旧资料需本人选择并重新审核。');}
async function settings(){const c=wrap('一个入口，同一份完整后端'),s=await status();c.append(E('p','本地和Vercel均运行 index.py → unified.app → jinshu.runtime.Runtime。前端不再执行BM25或财务计算。MongoDB保管事实、任务与发布；Redis保管会话与队列；Milvus保管可重建语义索引。'),details('实际运行状态（不包含密钥）',s),button('重新检查配置',()=>mount('settings')),button('备份当前浏览器的V7旧数据',exportLegacy));if(token&&user.role==='admin')c.append(button('验证数据库与缓存连接',async()=>c.append(details('真实服务检查',await api('connection-check','POST')))),button('同意一次真实模型连接测试',async()=>{if(confirm('将调用你配置的模型，可能产生少量费用。使用公开连接测试文字，继续？'))c.append(details('实际模型返回',await api('model-check','POST',{consent:true})));}));const help=E('div');help.append(E('p','部署者先在Vercel配置环境变量，再创建编辑与独立复核账号。没有任何公开默认密码。初始化口令只使用一次，请勿上传GitHub或发在聊天中。'));const[ul,u]=field('新账号'),[pl,p]=field('新密码（至少12位）','password'),[bl,b]=field('一次性初始化口令','password'),role=select([['student','部门成员'],['admin','编辑/审核管理员']]),dept=select([['','全局（仅管理员）'],['dept_wealth','理财产品'],['dept_release','发行报表'],['dept_risk','准入风控'],['dept_service','客服知识']]);help.append(ul,pl,bl,role,dept,button('创建账号（需部署者初始化授权）',async()=>{const r=await fetch('/api/setup/user',{method:'POST',headers:{'Content-Type':'application/json','X-Setup-Token':b.value},body:JSON.stringify({username:u.value,password:p.value,role:role.value,dept_id:dept.value})});const j=await r.json();if(!r.ok)throw Error(JSON.stringify(j.detail));p.value='';b.value='';notice('账号已建立。完成两个账号后删除Vercel初始化口令。');}));c.append(details('首次部署：创建账号',help));}
const renderers={ask,tasks:taskView,docs,memory,loop,traces,ops,pilot,settings};
status().then(s=>mount(s.configured?'ask':'settings')).catch(e=>notice('后端无法访问：'+e.message));
