/** Simple manual deploy from a clean runtime copy. Existing project links are reused. */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { createInterface } from 'node:readline/promises';
import { fileURLToPath } from 'node:url';
import { prepareDeployment } from './prepare_deployment.mjs';

export const CLI_VERSION = '60.1.3';

export function targetFromChoice(choice) {
  if (choice === undefined || choice === '' || choice === '1' || choice === 'preview') return 'preview';
  if (choice === '2' || choice === 'production') return 'production';
  if (choice === '0') return null;
  throw new Error('只支持 preview / production / 0。');
}

export function deployArguments(target, confirmation = '') {
  if (target === 'preview') return ['deploy', '--yes', '--logs'];
  if (target === 'production') {
    if (confirmation !== 'DEPLOY PRODUCTION') throw new Error('未收到 DEPLOY PRODUCTION；未发布正式版。');
    return ['deploy', '--yes', '--logs', '--prod'];
  }
  throw new Error('Unknown target');
}

function cli(args, cwd, {quiet=false}={}) {
  const npxArgs = ['--yes', `vercel@${CLI_VERSION}`, ...args];
  let command, commandArgs;
  if (process.platform === 'win32') {
    command = process.env.ComSpec || 'cmd.exe';
    // Every token is generated by this script; no user text is interpolated.
    commandArgs = ['/d', '/s', '/c', ['npx', ...npxArgs].join(' ')];
  } else {
    command = 'npx';
    commandArgs = npxArgs;
  }
  const result = spawnSync(command, commandArgs, {
    cwd, stdio: quiet ? 'pipe' : 'inherit', encoding: quiet ? 'utf8' : undefined,
    shell: false, env: process.env
  });
  if (result.error) throw new Error('Vercel CLI 无法启动，请检查 Node/npm 和网络。');
  if (result.status !== 0) {
    if (quiet && result.stderr) process.stderr.write(result.stderr);
    throw new Error('Vercel CLI 失败；以上方原始错误为准。');
  }
  return result;
}

function copyLink(localLink, staged) {
  if (fs.lstatSync(localLink).isSymbolicLink() || fs.lstatSync(path.dirname(localLink)).isSymbolicLink())
    throw new Error('本地项目关联不可为符号链接。');
  const link = JSON.parse(fs.readFileSync(localLink, 'utf8'));
  if (!link.projectId || !link.orgId) throw new Error('本地 Vercel 项目关联无效。');
  fs.mkdirSync(path.join(staged, '.vercel'), { recursive: true });
  fs.writeFileSync(path.join(staged, '.vercel', 'project.json'), JSON.stringify({
    orgId: link.orgId, projectId: link.projectId, projectName: link.projectName
  }, null, 2));
  return link;
}

export function cleanupTemporary(temporary, remove = fs.rmSync, warn = console.warn) {
  try {
    remove(temporary, {recursive: true, force: true, maxRetries: 8, retryDelay: 250});
    return true;
  } catch {
    warn(`临时目录暂未删除，可稍后手工清理：${temporary}`);
    return false;
  }
}

async function main() {
  if (process.argv.includes('--help')) {
    console.log('双击 deploy_vercel.bat 默认发布 Preview。\n正式版：deploy_vercel.bat production（需输入 DEPLOY PRODUCTION）。\n首次运行才会要求选择 Vercel 项目；之后自动复用。');
    return;
  }
  if (Number(process.versions.node.split('.')[0]) < 22) throw new Error('请先安装 Node.js 22 或更高版本。');

  const target = targetFromChoice(process.argv[2]);
  if (!target) return;

  const root = fileURLToPath(new URL('..', import.meta.url));
  const localLink = path.join(root, '.vercel', 'project.json');
  let temporary;
  try {
    temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'jinshu-release-'));
    const staged = path.join(temporary, 'runtime');
    prepareDeployment(root, staged);

    let link;
    if (fs.existsSync(localLink)) {
      link = copyLink(localLink, staged);
      console.log(`复用已关联项目：${link.projectName || link.projectId}`);
    } else {
      if (!process.stdin.isTTY) throw new Error('首次发布需要交互选择已有 Vercel 项目。');
      console.log('首次发布：请选择你已有的 Vercel 项目。建议选择现有工作台项目，不要新建重复项目。');
      cli(['link'], staged);
      const stagedLink = path.join(staged, '.vercel', 'project.json');
      if (!fs.existsSync(stagedLink)) throw new Error('没有生成有效的 Vercel 项目关联。');
      link = JSON.parse(fs.readFileSync(stagedLink, 'utf8'));
      if (!link.projectId || !link.orgId) throw new Error('没有有效项目关联。');
      fs.mkdirSync(path.dirname(localLink), { recursive: true });
      fs.writeFileSync(localLink, JSON.stringify({
        orgId: link.orgId, projectId: link.projectId, projectName: link.projectName
      }, null, 2));
    }

    console.log(`目标：${link.projectName || link.projectId}\n环境：${target}\n运行模式：金枢 V9 core（不依赖 MongoDB / Milvus）`);

    // Read-only target check, then a dry run. Both fail before any real deployment.
    console.log('核对项目和部署配置…');
    cli(['project', 'inspect', '--non-interactive'], staged);
    cli(['deploy', '--dry'], staged);

    let confirmation = '';
    if (target === 'production') {
      console.log('公开分享前请设置 JINSHU_ACCESS_CODE 和 Vercel 费用限制；仅凭页面可访问就能消耗模型额度。');
      if (!process.stdin.isTTY) throw new Error('正式发布需要交互确认。');
      const prompt = createInterface({ input: process.stdin, output: process.stdout });
      try { confirmation = (await prompt.question('输入 DEPLOY PRODUCTION 才会替换正式版：')).trim(); }
      finally { prompt.close(); }
    } else {
      console.log('运行文件与配置检查通过，开始发布 Preview（模型连通性仍需上线后测试）…');
    }

    cli(deployArguments(target, confirmation), staged);
    console.log('发布命令成功结束。请打开上方 URL，再检查 /api/status 和真实服务状态。');
  } finally {
    if (temporary) cleanupTemporary(temporary);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  main().catch(error => { console.error(error.message); process.exitCode = 1; });
